apiVersion: v1
kind: Template
labels:
  template: patch-custom-build-template
metadata:
  annotations:
    description: This example shows how to put a patch on image.
  creationTimestamp: null
  name: patch-custom-build-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      git:
        uri: ${PATCH_FILE_URL}
      type: Git
    strategy:
      customStrategy:
        forcePull: true
        env:
        - name: BUILD_BASE_IMAGE_NAME
          value: ${BUILD_BASE_IMAGE_NAME}
        - name: PATCH_COMMAND
          value: ${PATCH_COMMAND}
        - name: RUN_COMMAND
          value: ${RUN_COMMAND}
        exposeDockerSocket: true
        from:
          kind: DockerImage
          name: openshift3/patch-custom-docker-builder:v3.2.1.1
      type: Custom
    triggers:
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: generic
    - type: ConfigChange
  status:
    lastVersion: 0
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: jws-app
- description: The name of base image.
  name: BUILD_BASE_IMAGE_NAME
  required: true
  value: umetrip-jboss-webserver-3/jboss-webserver30-tomcat7-umetrip:2.0
- description: source patch URI for application(.tar.gz),please use -zcpPf
  name: PATCH_FILE_URL
  required: true
  value: http://192.168.40.102:8089/wars/test.tar.gz
- description: define how to execute patch package,default unzip
  name: PATCH_COMMAND
- description: define dockerfile run command,default (patch_command /tmp/PKG_NAME)
  name: RUN_COMMAND
- description: Generic build trigger secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_WEBHOOK_SECRET
  required: true
